# batchsize
batchSz: 64

# the place to save, default is None
save: null

# the default work dir
work: work

# random seed, default is 1
seed: 1

# number of epoch, default is 1000
nEpoch: 10

# weightDecay, default is 1e-4
weightDecay: 1.e-4

# optimizer, default is sgd
opt: sgd

# dataset
dataset: cifar-10

# number of users
num_users: 1

# fraction of users for federal optimization
frac: 0.1

# whether the data is iid
iid: True

# local epoch
local_ep: 1

# if False, no output of local update will be printed
verbose: True

# model
model_hparam:
  # lenet
  model_name: lenet
  nHidden: 50
  proj: softmax

  

