# batchsize
batchSz: 64

# the place to save, default is None
save: null

# random seed, default is 1
seed: 1

# number of epoch, default is 1000
nEpoch: 5

# weightDecay, default is 1e-4
weightDecay: 1.e-4

# optimizer, default is sgd
opt: adam

# dataset
dataset: cifar-10

# number of users
num_users: 5

# fraction of users for federal optimization
frac: 0.1

# whether the data is iid
iid: True

# local epoch
local_ep: 2

# if False, no output of local update will be printed
verbose: True

model_name: fc

nHidden: 500
# batch norm
bn: False

  

